framework:
    messenger:
        serializer:
            symfony_serializer:
                context:
                    default_constructor_arguments:
                        Cicada\Elasticsearch\Framework\Indexing\IndexerOffset:
                            mappingDefinitions: [ ]
